### ISSUE TITLE
Menu Layout

### ISSUE THREAD

**Issue by expandables2** [Aloshi/EmulationStation#334] opened 2015-01-04 17:54 UTC
Aloshi can you make the next release to have an option to change the menu from horizontal to vertical and carousel? By Carousel meaning the menu layout of Hyperspin http://www.hyperspin-fe.com/

**Comment by ProfessorKaos64** [comment] 2015-01-04 19:22
This is semi-duplicate of my [issue](https://github.com/Aloshi/EmulationStation/issues/319)

**Comment by nilsbyte** [comment] 2015-01-08 07:59
Are you speaking of the Main Menu or the Platform screens which are arranged in a carousel slide style?

**Comment by expandables2** [comment] 2015-01-09 03:09
The main menu i guess. Where for example the game lists are where you select a game can that menu be change to hyperspin menu?

**Comment by nilsbyte** [comment] 2015-01-16 18:24
That's not the main menu. It's the gamelist of a selected platform. You can try to come near a similar layout with the theming language of EmulationStation, but animation isn't possible.

If you want it to look like Hyperspin, you should use Hyperspin. :) For me, personally, Hyperspin is like a overdose of a mind-altering drug. Too colorful and too loud (visually speaking).

**Closed by nilsbyte** 2015-01-16 18:24 UTC
